In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import squareform, pdist
dataset_or = pd.read_excel(r"C:\Users\ASHWIK.ACHARYA\Brillio\Mohana Datla - CRED\python script\KPI Mapping.xlsx",sheet_name= "Report_KPI Mapping")

In [2]:

#Filtering data for Fact tables
if 'Table Type' in dataset_or.columns:
    dataset = dataset_or[dataset_or["Table Type"]!="Dimension Table"]

dataset = dataset[["Domain","Report Name","KPI/Used Columns"]].dropna().reset_index()
dataset = dataset[dataset["Domain"].isin(["Customer Support","Human Resources","Wallet","Product"])]
dataset["Domain report name"] = dataset["Domain"] +" \_/ "+ dataset["Report Name"]
dataset = dataset[["Domain report name","KPI/Used Columns"]].dropna().reset_index()
dataset.drop(["index"],axis=1,inplace=True)

# matrix = pd.get_dummies(dataset['KPI/Used Columns'],sparse = True ,dtype=int)
dataset = pd.concat([dataset, pd.get_dummies(dataset['KPI/Used Columns'],sparse = True ,dtype=int)], axis=1).groupby('Domain report name').sum()

#grp = dataset.groupby('Report Name').sum()
dataset.drop('KPI/Used Columns',axis=1,inplace=True)
dist = pdist(dataset, metric="cosine")
s_dist = squareform(dist)

# Fill diagonals with nulls
# np.fill_diagonal(s_dist, 2)
sim = np.subtract(1, s_dist)
dataset = pd.DataFrame(sim, columns=dataset.index, index=dataset.index)
#dataset = dataset.where(np.triu(np.ones(dataset.shape)).astype(np.bool_))
#dataset.reset_index(inplace=True,drop =True)
display(dataset)
"""#Keep only top similar reports
for i in dataset.columns:
    if i!='Domain report name':
        m = max(dataset[i])
        for j in range(len(dataset[i])):
            if not np.isnan(dataset[i][j]) and m != dataset[i][j]:
                dataset.loc[j,i]=0"""

Domain report name,Customer Support \_/ 01 Dayforce Call Driver Analysis,Customer Support \_/ 02 Call Drivers by Module,Customer Support \_/ 03 Call Drivers by Module First Year Clients,Customer Support \_/ 04 Call Drivers by Client Group,Customer Support \_/ 05 Call Drivers by Specialty Team,Customer Support \_/ 06 Client Tenure Ticket Metrics,Customer Support \_/ 07 Support Team Metrics,Customer Support \_/ 08 Appendix,Customer Support \_/ 2022 KB Topics Report,Customer Support \_/ 2022 Other Initiatives,...,Wallet \_/ Dayforce Wallet Phase Potential Activity,Wallet \_/ Dayforce Wallet Phase Potential Activity DEV,Wallet \_/ Dayforce Wallet Product Dataset,Wallet \_/ Dayforce Wallet Shared Dataset,Wallet \_/ Dayforce Wallet v2,Wallet \_/ DayforceWallet_DirectDeposit_WoW,Wallet \_/ Instant Issue Inventory,Wallet \_/ Wallet Direct Deposit Audit,Wallet \_/ Wallet Direct Marketing List,Wallet \_/ Wallet_DevReports
Domain report name,,,,,,,,,,,,,,,,,,,,,
Customer Support \_/ 01 Dayforce Call Driver Analysis,1.000000,0.739310,0.739310,0.759932,0.726224,0.340810,0.0,0.545837,0.023932,0.214351,...,0.007910,0.007910,0.010336,0.007910,0.007910,0.007910,0.013541,0.032108,0.000000,0.008169
Customer Support \_/ 02 Call Drivers by Module,0.739310,1.000000,1.000000,0.956089,0.946580,0.417786,0.0,0.575642,0.031782,0.074911,...,0.010505,0.010505,0.013726,0.010505,0.010505,0.010505,0.017983,0.042640,0.000000,0.010848
Customer Support \_/ 03 Call Drivers by Module First Year Clients,0.739310,1.000000,1.000000,0.956089,0.946580,0.417786,0.0,0.575642,0.031782,0.074911,...,0.010505,0.010505,0.013726,0.010505,0.010505,0.010505,0.017983,0.042640,0.000000,0.010848
Customer Support \_/ 04 Call Drivers by Client Group,0.759932,0.956089,0.956089,1.000000,0.956558,0.474644,0.0,0.602080,0.030949,0.072948,...,0.010230,0.010230,0.013367,0.010230,0.010230,0.010230,0.017512,0.041523,0.000000,0.010564
Customer Support \_/ 05 Call Drivers by Specialty Team,0.726224,0.946580,0.946580,0.956558,1.000000,0.410391,0.0,0.565453,0.000000,0.073585,...,0.010319,0.010319,0.013483,0.010319,0.010319,0.010319,0.017665,0.041885,0.000000,0.010656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallet \_/ DayforceWallet_DirectDeposit_WoW,0.007910,0.010505,0.010505,0.010230,0.010319,0.020116,0.0,0.012318,0.018363,0.008657,...,1.000000,1.000000,0.741541,1.000000,1.000000,1.000000,0.573205,0.012318,0.152092,0.897879
Wallet \_/ Instant Issue Inventory,0.013541,0.017983,0.017983,0.017512,0.017665,0.034435,0.0,0.021087,0.020956,0.009879,...,0.573205,0.573205,0.590570,0.573205,0.573205,0.573205,1.000000,0.028116,0.180512,0.595490
Wallet \_/ Wallet Direct Deposit Audit,0.032108,0.042640,0.042640,0.041523,0.041885,0.081650,0.0,0.050000,0.000000,0.000000,...,0.012318,0.012318,0.016096,0.012318,0.012318,0.012318,0.028116,1.000000,0.000000,0.012721
Wallet \_/ Wallet Direct Marketing List,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.152092,0.152092,0.198726,0.152092,0.152092,0.152092,0.180512,0.000000,1.000000,0.163338
Wallet \_/ Wallet_DevReports,0.008169,0.010848,0.010848,0.010564,0.010656,0.020773,0.0,0.012721,0.018963,0.013409,...,0.897879,0.897879,0.790314,0.897879,0.897879,0.897879,0.595490,0.012721,0.163338,1.000000

"#Keep only top similar reports\nfor i in dataset.columns:\n    if i!='Domain report name':\n        m = max(dataset[i])\n        for j in range(len(dataset[i])):\n            if not np.isnan(dataset[i][j]) and m != dataset[i][j]:\n                dataset.loc[j,i]=0"

In [3]:
datasetf = dataset
datasetf.reset_index(inplace=True,drop =True)
datasetf['Reports'] = datasetf.columns
display(datasetf)

Domain report name,Customer Support \_/ 01 Dayforce Call Driver Analysis,Customer Support \_/ 02 Call Drivers by Module,Customer Support \_/ 03 Call Drivers by Module First Year Clients,Customer Support \_/ 04 Call Drivers by Client Group,Customer Support \_/ 05 Call Drivers by Specialty Team,Customer Support \_/ 06 Client Tenure Ticket Metrics,Customer Support \_/ 07 Support Team Metrics,Customer Support \_/ 08 Appendix,Customer Support \_/ 2022 KB Topics Report,Customer Support \_/ 2022 Other Initiatives,...,Wallet \_/ Dayforce Wallet Phase Potential Activity DEV,Wallet \_/ Dayforce Wallet Product Dataset,Wallet \_/ Dayforce Wallet Shared Dataset,Wallet \_/ Dayforce Wallet v2,Wallet \_/ DayforceWallet_DirectDeposit_WoW,Wallet \_/ Instant Issue Inventory,Wallet \_/ Wallet Direct Deposit Audit,Wallet \_/ Wallet Direct Marketing List,Wallet \_/ Wallet_DevReports,Reports
0,1.000000,0.739310,0.739310,0.759932,0.726224,0.340810,0.0,0.545837,0.023932,0.214351,...,0.007910,0.010336,0.007910,0.007910,0.007910,0.013541,0.032108,0.000000,0.008169,Customer Support \_/ 01 Dayforce Call Driver A...
1,0.739310,1.000000,1.000000,0.956089,0.946580,0.417786,0.0,0.575642,0.031782,0.074911,...,0.010505,0.013726,0.010505,0.010505,0.010505,0.017983,0.042640,0.000000,0.010848,Customer Support \_/ 02 Call Drivers by Module
2,0.739310,1.000000,1.000000,0.956089,0.946580,0.417786,0.0,0.575642,0.031782,0.074911,...,0.010505,0.013726,0.010505,0.010505,0.010505,0.017983,0.042640,0.000000,0.010848,Customer Support \_/ 03 Call Drivers by Module...
3,0.759932,0.956089,0.956089,1.000000,0.956558,0.474644,0.0,0.602080,0.030949,0.072948,...,0.010230,0.013367,0.010230,0.010230,0.010230,0.017512,0.041523,0.000000,0.010564,Customer Support \_/ 04 Call Drivers by Client...
4,0.726224,0.946580,0.946580,0.956558,1.000000,0.410391,0.0,0.565453,0.000000,0.073585,...,0.010319,0.013483,0.010319,0.010319,0.010319,0.017665,0.041885,0.000000,0.010656,Customer Support \_/ 05 Call Drivers by Specia...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,0.007910,0.010505,0.010505,0.010230,0.010319,0.020116,0.0,0.012318,0.018363,0.008657,...,1.000000,0.741541,1.000000,1.000000,1.000000,0.573205,0.012318,0.152092,0.897879,Wallet \_/ DayforceWallet_DirectDeposit_WoW
127,0.013541,0.017983,0.017983,0.017512,0.017665,0.034435,0.0,0.021087,0.020956,0.009879,...,0.573205,0.590570,0.573205,0.573205,0.573205,1.000000,0.028116,0.180512,0.595490,Wallet \_/ Instant Issue Inventory
128,0.032108,0.042640,0.042640,0.041523,0.041885,0.081650,0.0,0.050000,0.000000,0.000000,...,0.012318,0.016096,0.012318,0.012318,0.012318,0.028116,1.000000,0.000000,0.012721,Wallet \_/ Wallet Direct Deposit Audit
129,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.152092,0.198726,0.152092,0.152092,0.152092,0.180512,0.000000,1.000000,0.163338,Wallet \_/ Wallet Direct Marketing List
130,0.008169,0.010848,0.010848,0.010564,0.010656,0.020773,0.0,0.012721,0.018963,0.013409,...,0.897879,0.790314,0.897879,0.897879,0.897879,0.595490,0.012721,0.163338,1.000000,Wallet \_/ Wallet_DevReports

In [4]:

Domain_Dataset = pd.melt(datasetf, id_vars = 'Reports')
Domain_Dataset.dropna(inplace=True)
display(Domain_Dataset)

,Reports,Domain report name,value
0,Customer Support \_/ 01 Dayforce Call Driver A...,Customer Support \_/ 01 Dayforce Call Driver A...,1.000000
1,Customer Support \_/ 02 Call Drivers by Module,Customer Support \_/ 01 Dayforce Call Driver A...,0.739310
2,Customer Support \_/ 03 Call Drivers by Module...,Customer Support \_/ 01 Dayforce Call Driver A...,0.739310
3,Customer Support \_/ 04 Call Drivers by Client...,Customer Support \_/ 01 Dayforce Call Driver A...,0.759932
4,Customer Support \_/ 05 Call Drivers by Specia...,Customer Support \_/ 01 Dayforce Call Driver A...,0.726224
...,...,...,...
17156,Wallet \_/ DayforceWallet_DirectDeposit_WoW,Wallet \_/ Wallet_DevReports,0.897879
17157,Wallet \_/ Instant Issue Inventory,Wallet \_/ Wallet_DevReports,0.595490
17158,Wallet \_/ Wallet Direct Deposit Audit,Wallet \_/ Wallet_DevReports,0.012721
17159,Wallet \_/ Wallet Direct Marketing List,Wallet \_/ Wallet_DevReports,0.163338
17160,Wallet \_/ Wallet_DevReports,Wallet \_/ Wallet_DevReports,1.000000

In [5]:
dataset = Domain_Dataset[Domain_Dataset['value'] > 0.75]

In [6]:
dataset['Domain'] = dataset['Reports'].str.split("\_/", n=1, expand=True)[0]
dataset['Report 1'] = dataset['Reports'].str.split("\_/", n=1, expand=True)[1]
dataset['Report 2'] = dataset['Domain report name'].str.split("\_/", n=1, expand=True)[1]
dataset = dataset.drop(['Reports','Domain report name'],axis=1)

C:\Users\ASHWIK.ACHARYA\AppData\Local\Temp\ipykernel_24752\2995467168.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Domain'] = dataset['Reports'].str.split("\_/", n=1, expand=True)[0]
C:\Users\ASHWIK.ACHARYA\AppData\Local\Temp\ipykernel_24752\2995467168.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Report 1'] = dataset['Reports'].str.split("\_/", n=1, expand=True)[1]
C:\Users\ASHWIK.ACHARYA\AppData\Local\Temp\ipykernel_24752\2995467168.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Report 2'] = dataset['Domain report name'].str.split("\_/", n=1, expand=True)[1]

In [7]:
display(dataset)

,value,Domain,Report 1,Report 2
0,1.000000,Customer Support \,01 Dayforce Call Driver Analysis,01 Dayforce Call Driver Analysis
3,0.759932,Customer Support \,04 Call Drivers by Client Group,01 Dayforce Call Driver Analysis
132,1.000000,Customer Support \,02 Call Drivers by Module,02 Call Drivers by Module
133,1.000000,Customer Support \,03 Call Drivers by Module First Year Clients,02 Call Drivers by Module
134,0.956089,Customer Support \,04 Call Drivers by Client Group,02 Call Drivers by Module
...,...,...,...,...
17153,0.790314,Wallet \,Dayforce Wallet Product Dataset,Wallet_DevReports
17154,0.897879,Wallet \,Dayforce Wallet Shared Dataset,Wallet_DevReports
17155,0.897879,Wallet \,Dayforce Wallet v2,Wallet_DevReports
17156,0.897879,Wallet \,DayforceWallet_DirectDeposit_WoW,Wallet_DevReports
17160,1.000000,Wallet \,Wallet_DevReports,Wallet_DevReports

In [8]:
dataset['Cluster'] = dataset.groupby(['Report 2']).ngroup()
display(dataset)

,value,Domain,Report 1,Report 2,Cluster
0,1.000000,Customer Support \,01 Dayforce Call Driver Analysis,01 Dayforce Call Driver Analysis,0
3,0.759932,Customer Support \,04 Call Drivers by Client Group,01 Dayforce Call Driver Analysis,0
132,1.000000,Customer Support \,02 Call Drivers by Module,02 Call Drivers by Module,1
133,1.000000,Customer Support \,03 Call Drivers by Module First Year Clients,02 Call Drivers by Module,1
134,0.956089,Customer Support \,04 Call Drivers by Client Group,02 Call Drivers by Module,1
...,...,...,...,...,...
17153,0.790314,Wallet \,Dayforce Wallet Product Dataset,Wallet_DevReports,126
17154,0.897879,Wallet \,Dayforce Wallet Shared Dataset,Wallet_DevReports,126
17155,0.897879,Wallet \,Dayforce Wallet v2,Wallet_DevReports,126
17156,0.897879,Wallet \,DayforceWallet_DirectDeposit_WoW,Wallet_DevReports,126
17160,1.000000,Wallet \,Wallet_DevReports,Wallet_DevReports,126

In [9]:
clist = []
dataset = dataset.sort_values(by=['Cluster'])
for i in dataset.Cluster.unique():
    df = dataset[dataset['Cluster'] == i ]
    df.reset_index(drop=True, inplace=True) 
    clist.append(list(df['Report 1']))

print(clist)

[[' 01 Dayforce Call Driver Analysis', ' 04 Call Drivers by Client Group'], [' 02 Call Drivers by Module', ' 03 Call Drivers by Module First Year Clients', ' 04 Call Drivers by Client Group', ' 05 Call Drivers by Specialty Team'], [' 02 Call Drivers by Module', ' 03 Call Drivers by Module First Year Clients', ' 04 Call Drivers by Client Group', ' 05 Call Drivers by Specialty Team'], [' 05 Call Drivers by Specialty Team', ' 04 Call Drivers by Client Group', ' 02 Call Drivers by Module', ' 01 Dayforce Call Driver Analysis', ' 03 Call Drivers by Module First Year Clients'], [' 02 Call Drivers by Module', ' 03 Call Drivers by Module First Year Clients', ' 04 Call Drivers by Client Group', ' 05 Call Drivers by Specialty Team'], [' 06 Client Tenure Ticket Metrics'], [' 07 Support Team Metrics'], [' 08 Appendix'], [' 2019 Pass Chart'], [' 2022 Annual Analysis Tool NR Oct 19'], [' 2022 Dayforce Product Roadmap Delivery'], [' 2022 KB Topics Report'], [' TAM TFS Report_v2', ' Enterprise Call Driver Report', ' 2022 Other Initiatives', ' XCL'], [' 2022 WFM Initiative Cases'], [' EmployeeExperienceComments_10182022', ' 2022EngagementCommentsAnalysis'], [' Team Metrics', ' Team Metrics - Sample', ' Team Metrics-testing cred', ' ANZ Release Criteria Summary'], [' Accessibility Burndown Chart'], [' Activate Install Counts'], [' Aha Analysis', ' Dayforce Client Ideas', ' Dayforce Staff Ideas'], [' Aha Features by Initiatve Type', ' Dependency Reporting'], [' ArticleThemesNLP_PBI'], [' Automated Acceptance Test Results'], [' Cloud Hosting Upgrades', ' Azure Migration Tracker 2022_v2'], [' Azure Spend Summary', ' Azure Spend Summary - P&T', ' AzureCostManagementApp'], [' Azure Spend Summary', ' Azure Spend Summary - P&T', ' AzureCostManagementApp'], [' Azure Spend Summary', ' Azure Spend Summary - P&T', ' AzureCostManagementApp'], [' BenefitsADOItemsForTeamReview'], [' Bug Analysis'], [' Bugs Per Release'], [' CARL  Ticket Trends'], [' CM Salesforce Case Reports', ' Cloud Hosting Cases'], [' COO Data 2022'], [' CVT Rules Report'], [' CWW_Dashboard'], [' CXI Ticket Report - New', ' TAM Ticket Report V2', ' Tax Fallout Report'], [' Call Driver Data Corp Strategy'], [' Call Drivers KPI'], [' Capitalization - Finance Actual vs Target'], [' Client Bugs With Development'], [' Client Defect Cycle Time'], [' Cloud Hosting Cases', ' CM Salesforce Case Reports'], [' Azure Migration Tracker 2022_v2', ' Cloud Hosting Upgrades'], [' Coronavirus in US'], [' DF Hub Adoption'], [' Dashboard'], [' Data Management Detail'], [' Dayforce Client Ideas', ' Dayforce Staff Ideas', ' Aha Analysis'], [' Dayforce Errors'], [' Product Briefs', ' PowerBI - JIRA Base Template', ' Jira Dependency Reporting', ' Dayforce Release Review', ' Dayforce Release Planning & Review'], [' Jira Dependency Reporting', ' PowerBI - JIRA Base Template', ' Dayforce Release Review', ' Dayforce Release Planning & Review', ' Product Briefs'], [' Dayforce Client Ideas', ' Aha Analysis', ' Dayforce Staff Ideas'], [' Dayforce Wallet - AuthTrans'], [' Dayforce Wallet - AuthTrans  - AD HOC'], [' Dayforce Wallet - Central Transactions'], [' Instant Issue Inventory', ' Dayforce Wallet - New Requests'], [' Dayforce Wallet CSM Report', ' Wallet_DevReports', ' DayforceWallet_DirectDeposit_WoW', ' Dayforce Wallet v2', ' Dayforce Wallet Shared Dataset', ' Dayforce Wallet Product Dataset', ' Dayforce Wallet - Risk Management', ' Dayforce Wallet Phase Potential Activity', ' Dayforce Wallet Phase Potential Activity DEV'], [' Dayforce Wallet - Trust'], [' Dayforce Wallet - Trust - Total Activities'], [' Dayforce Wallet Bank Audit'], [' DayforceWallet_DirectDeposit_WoW', ' Dayforce Wallet v2', ' Dayforce Wallet Shared Dataset', ' Dayforce Wallet Phase Potential Activity DEV', ' Dayforce Wallet Phase Potential Activity', ' Dayforce Wallet CSM Report', ' Dayforce Wallet - Risk Management', ' Wallet_DevReports'], [' Dayforce Wallet v2', ' DayforceWallet_DirectDeposit_WoW', ' Dayforce Wallet - Risk Management', ' Dayforce Wallet CSM Report', ' Wallet_DevReports', ' Dayforce Wallet Phase Potential Activity DEV', ' Dayforce Wallet Phase Potential Activity', ' Dayforce Wallet Shared Dataset'], [' Wallet_DevReports', ' DayforceWallet_DirectDeposit_WoW', ' Dayforce Wallet v2', ' Dayforce Wallet Phase Potential Activity DEV', ' Dayforce Wallet Phase Potential Activity', ' Dayforce Wallet Shared Dataset', ' Dayforce Wallet - Risk Management', ' Dayforce Wallet CSM Report'], [' Dayforce Wallet - Risk Management', ' Wallet_DevReports', ' Dayforce Wallet Product Dataset'], [' Dayforce Wallet Phase Potential Activity DEV', ' Dayforce Wallet Shared Dataset', ' Dayforce Wallet v2', ' DayforceWallet_DirectDeposit_WoW', ' Wallet_DevReports', ' Dayforce Wallet Phase Potential Activity', ' Dayforce Wallet CSM Report', ' Dayforce Wallet - Risk Management'], [' DayforceWallet_DirectDeposit_WoW', ' Dayforce Wallet Shared Dataset', ' Dayforce Wallet Phase Potential Activity DEV', ' Dayforce Wallet Phase Potential Activity', ' Dayforce Wallet CSM Report', ' Dayforce Wallet - Risk Management', ' Wallet_DevReports', ' Dayforce Wallet v2'], [' Wallet_DevReports', ' Dayforce Wallet Shared Dataset', ' DayforceWallet_DirectDeposit_WoW', ' Dayforce Wallet CSM Report', ' Dayforce Wallet Phase Potential Activity', ' Dayforce Wallet v2', ' Dayforce Wallet Phase Potential Activity DEV', ' Dayforce Wallet - Risk Management'], [' Demo for Intro PBI Webinar'], [' Dependency Reporting', ' Aha Features by Initiatve Type'], [' EmployeeExperienceComments_10182022', ' 2022EngagementCommentsAnalysis'], [' 2022 Other Initiatives', ' Enterprise Call Driver Report', ' TAM TFS Report_v2', ' TAM Ticket Report V2', ' XCL'], [' Upgrade Project Dashboard', ' Existing Customers Moving to a New Release'], [' Export Listing'], [' FTS test - WIP', ' Major Incident Management Tracker'], [' Feature Reporting'], [' Feature Roadmap Burnup Chart'], [' Feature Status Tracking'], [' Feature and PBI - Lead and Cycle Time'], [' HR Active Employees by Senior Manager_wCountry'], [' HR Anniversary'], [' IndirectvsDirectReportsMapped'], [' Instant Issue Inventory', ' Dayforce Wallet - New Requests'], [' InternalMobility_updated'], [' Dayforce Release Planning & Review', ' Dayforce Release Review', ' Jira Dependency Reporting', ' PowerBI - JIRA Base Template', ' Product Briefs'], [' Support Data Reports', ' Legal Entity Lookup Report'], [' MFA Adoption and Usage'], [' FTS test - WIP', ' Major Incident Management Tracker'], [' Managed Services Onboarding Dashboard 2.0'], [' Managed Services Operational Excellence Dashboard'], [' Microsoft Forms Pro Customer Satisfaction'], [' NewDirectorPlus'], [' Nothing To See Here, Move Along'], [' Office Hours Report'], [' Open Bug Analysis'], [' P&T 2022 Goals'], [' P&T CM Requests (DB Restore, Deployment, Site Creation-Removal, Branch Build, SFTP Setup)'], [' P&T Headcount 2022'], [' P&T Headcount 2022 - Interns', ' P&T Leadership Dashboard - Exec Summary'], [' P&T Headcount 2022 - Interns', ' P&T Leadership Dashboard - Exec Summary'], [' PeopleIntelligenceUsage'], [' Dayforce Release Review', ' Dayforce Release Planning & Review', ' Jira Dependency Reporting', ' PowerBI - JIRA Base Template', ' Product Briefs'], [' PowerBIReport - Public Sector Acc Bugs'], [' Process Analytics for Dynamics 365'], [' Jira Dependency Reporting', ' Product Briefs', ' PowerBI - JIRA Base Template', ' Dayforce Release Review', ' Dayforce Release Planning & Review'], [' Product Usage Search'], [' Quality Dashboard'], [' RCA Issue Log Dashboard'], [' Release Impact Analysis'], [' Release Outcome Analysis'], [' Resilience Reports'], [' SOC_Analysis'], [' Search Analytics Dashboard Ver 1.1 no weekend trend'], [' Standard & Compliance Reports'], [' Legal Entity Lookup Report', ' Support Data Reports'], [' TA Metrics_updatedmapping'], [' 2022 Other Initiatives', ' Enterprise Call Driver Report', ' TAM TFS Report_v2', ' TAM Ticket Report V2', ' XCL'], [' CXI Ticket Report - New', ' TAM TFS Report_v2', ' TAM Ticket Report V2', ' Tax Fallout Report', ' XCL', ' Enterprise Call Driver Report'], [' CXI Ticket Report - New', ' TAM Ticket Report V2', ' Tax Fallout Report'], [' Team Metrics - Sample', ' ANZ Release Criteria Summary', ' Team Metrics-testing cred', ' Team Metrics'], [' ANZ Release Criteria Summary', ' Team Metrics - Sample', ' Team Metrics-testing cred', ' Team Metrics'], [' Team Metrics - Sample', ' ANZ Release Criteria Summary', ' Team Metrics-testing cred', ' Team Metrics'], [' Test Cases - Core Regression'], [' Testing JIRA History'], [' UAT Metrics'], [' Existing Customers Moving to a New Release', ' Upgrade Project Dashboard'], [' Wallet Direct Deposit Audit'], [' Wallet Direct Marketing List'], [' Dayforce Wallet Shared Dataset', ' Dayforce Wallet Product Dataset', ' Dayforce Wallet Phase Potential Activity DEV', ' Dayforce Wallet Phase Potential Activity', ' Dayforce Wallet CSM Report', ' Dayforce Wallet - Risk Management', ' Dayforce Wallet v2', ' DayforceWallet_DirectDeposit_WoW', ' Wallet_DevReports'], [' Web Services Usage'], [' XCL', ' TAM Ticket Report V2', ' TAM TFS Report_v2', ' Enterprise Call Driver Report', ' 2022 Other Initiatives'], [' call driver text analysis'], [' sla_overview_V1']]

In [10]:
pos = []
tst = []
for i in range(0,len(clist)):
    if i in pos:
        continue
    for j in range(i+1,len(clist)):
        if clist[i] == clist[j]:
            pos.append(j)
            tst.append(i)

print(pos)

[2, 4, 68, 24, 25, 116, 80, 114, 85, 97, 119]

In [11]:
print(tst)

[1, 1, 14, 23, 23, 34, 54, 69, 72, 96, 117]

In [12]:
finaldf = dataset[~dataset['Cluster'].isin(pos)]
finaldf['new'] = np.where((finaldf['Report 1'] == finaldf['Report 2']), 1, 0)

C:\Users\ASHWIK.ACHARYA\AppData\Local\Temp\ipykernel_24752\199857895.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finaldf['new'] = np.where((finaldf['Report 1'] == finaldf['Report 2']), 1, 0)

In [13]:
tempdf = finaldf[finaldf['new'] != 1]

In [14]:
idx = tempdf.groupby('Report 1')['value'].idxmax()
max_scores = tempdf.loc[idx]

In [15]:
max_scores = pd.concat([finaldf[finaldf['new'] == 1],max_scores], ignore_index=True)

In [16]:
max_scores.to_csv(r"C:\Users\ASHWIK.ACHARYA\Brillio\Mohana Datla - CRED\python script\finaldf.csv")
display(max_scores.sort_values(by=['Cluster']))

,value,Domain,Report 1,Report 2,Cluster,new
0,1.000000,Customer Support \,01 Dayforce Call Driver Analysis,01 Dayforce Call Driver Analysis,0,1
1,1.000000,Customer Support \,02 Call Drivers by Module,02 Call Drivers by Module,1,1
122,1.000000,Customer Support \,03 Call Drivers by Module First Year Clients,02 Call Drivers by Module,1,0
123,0.956089,Customer Support \,04 Call Drivers by Client Group,02 Call Drivers by Module,1,0
124,0.956558,Customer Support \,05 Call Drivers by Specialty Team,04 Call Drivers by Client Group,3,0
...,...,...,...,...,...,...
116,1.000000,Product \,Web Services Usage,Web Services Usage,127,1
150,1.000000,Customer Support \,Enterprise Call Driver Report,XCL,128,0
117,1.000000,Customer Support \,XCL,XCL,128,1
118,1.000000,Product \,call driver text analysis,call driver text analysis,129,1
119,1.000000,Customer Support \,sla_overview_V1,sla_overview_V1,130,1

In [17]:
display(max_scores.head(10))

,value,Domain,Report 1,Report 2,Cluster,new
0,1.0,Customer Support \,01 Dayforce Call Driver Analysis,01 Dayforce Call Driver Analysis,0,1
1,1.0,Customer Support \,02 Call Drivers by Module,02 Call Drivers by Module,1,1
2,1.0,Customer Support \,04 Call Drivers by Client Group,04 Call Drivers by Client Group,3,1
3,1.0,Customer Support \,06 Client Tenure Ticket Metrics,06 Client Tenure Ticket Metrics,5,1
4,1.0,Customer Support \,07 Support Team Metrics,07 Support Team Metrics,6,1
5,1.0,Customer Support \,08 Appendix,08 Appendix,7,1
6,1.0,Human Resources \,2019 Pass Chart,2019 Pass Chart,8,1
7,1.0,Human Resources \,2022 Annual Analysis Tool NR Oct 19,2022 Annual Analysis Tool NR Oct 19,9,1
8,1.0,Product \,2022 Dayforce Product Roadmap Delivery,2022 Dayforce Product Roadmap Delivery,10,1
9,1.0,Customer Support \,2022 KB Topics Report,2022 KB Topics Report,11,1

In [18]:
display(finaldf.head(10))

,value,Domain,Report 1,Report 2,Cluster,new
0,1.000000,Customer Support \,01 Dayforce Call Driver Analysis,01 Dayforce Call Driver Analysis,0,1
3,0.759932,Customer Support \,04 Call Drivers by Client Group,01 Dayforce Call Driver Analysis,0,0
132,1.000000,Customer Support \,02 Call Drivers by Module,02 Call Drivers by Module,1,1
133,1.000000,Customer Support \,03 Call Drivers by Module First Year Clients,02 Call Drivers by Module,1,0
134,0.956089,Customer Support \,04 Call Drivers by Client Group,02 Call Drivers by Module,1,0
135,0.946580,Customer Support \,05 Call Drivers by Specialty Team,02 Call Drivers by Module,1,0
397,0.956558,Customer Support \,05 Call Drivers by Specialty Team,04 Call Drivers by Client Group,3,0
396,1.000000,Customer Support \,04 Call Drivers by Client Group,04 Call Drivers by Client Group,3,1
394,0.956089,Customer Support \,02 Call Drivers by Module,04 Call Drivers by Client Group,3,0
393,0.759932,Customer Support \,01 Dayforce Call Driver Analysis,04 Call Drivers by Client Group,3,0